name: Run

on:
  workflow_dispatch:
  schedule:
    - cron: '0 8 * * *' 

jobs:
  run-python:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Python 3.13 with pip cache
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'
          cache: 'pip'
          cache-dependency-path: requirements.txt

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Jalanin main.py
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
        run: python main.py

      - name: Upload semua file parquet ke Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: hasil-parquet-${{ github.run_id }}
          path: |
            *.parquet
            output/*.parquet
          if-no-files-found: warn 
          retention-days: 14

  pop-country:
    needs: run-python
    if: success()
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Hapus kode negara pertama
        id: pop
        run: |
          REMOVED=$(jq -r '.queue[0]' countries.json)
          echo "removed=$REMOVED" >> $GITHUB_OUTPUT
          [ "$REMOVED" = "null" ] && exit 0
          jq 'del(.queue[0])' countries.json > tmp.json && mv tmp.json countries.json

      - name: Commit hasil
        if: steps.pop.outputs.removed!= 'null'
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore: ${{ steps.pop.outputs.removed }} removed after script [skip ci]"
          file_pattern: countries.json
